/**
 * Financial Document domain errors (IMP-028 / D-365).
 */

export type FinancialDocumentErrorCode =
  | "INVALID_STATUTORY_TYPE"
  | "TAX_RECEIPT_FORBIDDEN"
  | "INVALID_FINANCIAL_YEAR"
  | "CREDIT_NOTE_REQUIRES_PRIOR_TAX_INVOICE"
  | "BILL_OF_SUPPLY_CREDIT_NOTE_PROHIBITED"
  | "REFUND_VOUCHER_REQUIRES_PRIOR_RECEIPT_VOUCHER"
  | "ISSUANCE_IDEMPOTENCY_CONFLICT"
  | "STATUTORY_NUMBER_CONFLICT"
  | "STATUTORY_NUMBER_INVALID"
  | "NUMBERING_SERIES_NOT_FOUND"
  | "NUMBERING_SERIES_AMBIGUOUS"
  | "ISSUER_PROFILE_NOT_FOUND"
  | "ISSUER_PROFILE_AMBIGUOUS"
  | "ISSUER_PROFILE_NOT_ELIGIBLE"
  | "DOCUMENT_TYPE_DISABLED"
  | "ISSUANCE_POLICY_MISMATCH"
  | "ISSUER_PROFILE_INCOMPLETE"
  | "REVERSE_CHARGE_AUTHORITY_REQUIRED"
  | "RECIPIENT_PARTICULARS_REQUIRED"
  | "UNSUPPORTED_INTER_STATE_PARTICULARS"
  | "UPSTREAM_REFERENCE_INVALID"
  | "PRIOR_DOCUMENT_INVALID"
  | "ARITHMETIC_INVALID"
  | "TAX_COMPONENT_INVALID"
  | "INVALID_ISSUANCE_INPUT"
  | "INVALID_ACCESS_INPUT"
  | "DOCUMENT_NOT_FOUND"
  | "CUSTOMER_AUTH_REQUIRED"
  | "AUTHORITY_INCONSISTENT"
  | "IMMUTABLE_DOCUMENT_MUTATION_FORBIDDEN"
  | "RENDERING_FAILED"
  | "RENDERING_AUTHORITY_GAP"
  | "ARTIFACT_GENERATION_FAILED";

export class FinancialDocumentError extends Error {
  readonly code: FinancialDocumentErrorCode;

  constructor(code: FinancialDocumentErrorCode, message: string) {
    super(message);
    this.name = "FinancialDocumentError";
    this.code = code;
  }
}
