/**
 * Statutory Financial Document signing foundation errors (IMP-028 / D-367).
 */

export type SignatureFoundationErrorCode =
  | "INVALID_SIGNING_METHOD"
  | "INVALID_SIGNATURE_REQUIREMENT"
  | "INVALID_SIGNATURE_ARTIFACT_STATUS"
  | "INVALID_EFFECTIVE_DATE_RANGE"
  | "AUTHORISED_SIGNER_PROFILE_NOT_FOUND"
  | "SIGNATURE_ARTIFACT_NOT_FOUND"
  | "SIGNATURE_ARTIFACT_ALREADY_EXISTS"
  | "SIGNATURE_ARTIFACT_NOT_SIGNABLE"
  | "SIGNATURE_ARTIFACT_IMMUTABLE"
  | "SIGNATURE_ARTIFACT_SIGNED_INCOMPLETE"
  | "SIGNATURE_ARTIFACT_CONFLICT"
  | "SIGNATURE_ARTIFACT_IDEMPOTENCY_CONFLICT"
  | "FINANCIAL_DOCUMENT_NOT_FOUND"
  | "UPSTREAM_REFERENCE_INVALID"
  | "SIGNATURE_REQUIREMENT_POLICY_UNRESOLVED"
  | "SIGNATURE_REQUIREMENT_POLICY_CONFLICT"
  | "SIGNATURE_REJECTED_POLICY_UNRESOLVED"
  | "MANUAL_UPLOAD_ATTESTATION_REQUIRED"
  | "SIGNED_PDF_CONTAINER_INVALID"
  | "SIGNED_PDF_OVERSIZED"
  | "AUTHORISED_SIGNER_PROFILE_INELIGIBLE"
  | "AUTHORISED_SIGNER_LEGAL_ENTITY_MISMATCH"
  | "AUTHORISED_SIGNER_EFFECTIVE_WINDOW_VIOLATION"
  | "SIGNED_ARTIFACT_OBJECT_NOT_FOUND"
  | "SIGNED_ARTIFACT_HASH_MISMATCH";

export class SignatureFoundationError extends Error {
  readonly code: SignatureFoundationErrorCode;

  constructor(code: SignatureFoundationErrorCode, message: string) {
    super(message);
    this.name = "SignatureFoundationError";
    this.code = code;
  }
}
