#!/usr/bin/env bash
# BOBA Bear PostgreSQL entrypoint wrapper (IMP-037).
#
# Preserves upstream docker-entrypoint.sh behaviour. When
# BOBA_PGBACKREST_ARCHIVE=1, render a concrete /etc/pgbackrest/pgbackrest.conf
# BEFORE PostgreSQL can fire archive_command. Archive-push uses that same file.
# Heavy scheduled backups remain outside this path and use host-local flock;
# WAL archival must never wait on that lock.
#
# Production-shaped mode (default) fail-closes unless physical Spaces config is
# present. Disposable local tests must set BOBA_PGBACKREST_REPO_MODE=posix.
set -euo pipefail

ARCHIVE_ENABLED="${BOBA_PGBACKREST_ARCHIVE:-0}"
ARCHIVE_TIMEOUT="${BOBA_PGBACKREST_ARCHIVE_TIMEOUT:-300}"
STANZA="${BOBA_PGBACKREST_STANZA:-boba}"
CONFIG_PATH="/etc/pgbackrest/pgbackrest.conf"
RENDER_BIN="${BOBA_PGBACKREST_RENDER_BIN:-/usr/local/bin/boba-render-pgbackrest-conf}"

if [ "${ARCHIVE_ENABLED}" = "1" ]; then
  if [ ! -x "${RENDER_BIN}" ]; then
    echo "BOBA pgBackRest: ${RENDER_BIN} missing; refusing to start with archive_command" >&2
    exit 1
  fi
  if ! rendered="$("${RENDER_BIN}")"; then
    echo "BOBA pgBackRest: concrete config render failed; refusing to start PostgreSQL" >&2
    exit 1
  fi
  if [ -z "${rendered}" ]; then
    echo "BOBA pgBackRest: rendered config is empty; refusing to start PostgreSQL" >&2
    exit 1
  fi
  umask 077
  printf '%s\n' "${rendered}" > "${CONFIG_PATH}"
  chown postgres:postgres "${CONFIG_PATH}"
  chmod 640 "${CONFIG_PATH}"

  # Map host-local secrets into pgBackRest env names. Do not write them into the conf file.
  export PGBACKREST_REPO1_CIPHER_PASS="${PGBACKREST_CIPHER_PASS}"
  if [ "${BOBA_PGBACKREST_REPO_MODE:-s3}" != "posix" ] && [ "${BOBA_PGBACKREST_REPO_MODE:-s3}" != "local" ]; then
    export PGBACKREST_REPO1_S3_KEY="${BOBA_PHYSICAL_SPACES_ACCESS_KEY_ID}"
    export PGBACKREST_REPO1_S3_KEY_SECRET="${BOBA_PHYSICAL_SPACES_SECRET_ACCESS_KEY}"
  fi

  ARCHIVE_CMD="pgbackrest --config=${CONFIG_PATH} --stanza=${STANZA} archive-push %p"
  mkdir -p /etc/postgresql || true
  cat > /etc/postgresql/boba-archive.conf <<EOF
# Generated by boba-postgres-entrypoint (IMP-037). Do not edit by hand.
archive_mode = on
archive_timeout = ${ARCHIVE_TIMEOUT}
archive_command = '${ARCHIVE_CMD}'
EOF
  if [ "${1:-}" = "postgres" ] || [ "${1:-}" = "docker-entrypoint.sh" ]; then
    set -- "$@" -c "archive_mode=on" \
      -c "archive_timeout=${ARCHIVE_TIMEOUT}" \
      -c "archive_command=${ARCHIVE_CMD}"
  fi
fi

if [ -x /usr/local/bin/docker-entrypoint.sh ]; then
  exec /usr/local/bin/docker-entrypoint.sh "$@"
fi
exec docker-entrypoint.sh "$@"
