#!/usr/bin/env bash
# BOBA Bear PostgreSQL entrypoint wrapper (IMP-037).
#
# Preserves upstream docker-entrypoint.sh behaviour. When
# BOBA_PGBACKREST_ARCHIVE=1, appends archive settings for continuous WAL
# archival via pgBackRest archive-push. Heavy scheduled backups remain outside
# this path and use host-local flock; WAL archival must never wait on that lock.
set -euo pipefail

ARCHIVE_ENABLED="${BOBA_PGBACKREST_ARCHIVE:-0}"
ARCHIVE_TIMEOUT="${BOBA_PGBACKREST_ARCHIVE_TIMEOUT:-300}"
STANZA="${BOBA_PGBACKREST_STANZA:-boba}"

if [ "${ARCHIVE_ENABLED}" = "1" ]; then
  CONF_DIR="${PGDATA:-/var/lib/postgresql/data}"
  # Ensure conf.d exists for include_dir style configs when using default image layout.
  mkdir -p /etc/postgresql || true
  ARCHIVE_CONF="/etc/postgresql/boba-archive.conf"
  cat > "${ARCHIVE_CONF}" <<EOF
# Generated by boba-postgres-entrypoint (IMP-037). Do not edit by hand.
archive_mode = on
archive_timeout = ${ARCHIVE_TIMEOUT}
archive_command = 'pgbackrest --stanza=${STANZA} archive-push %p'
EOF
  # Pass via POSTGRES_INITDB_ARGS / command append when starting postgres.
  # For already-initialized clusters, operators must also ensure postgresql.conf
  # includes these settings (see imp037-recovery-runbook.md).
  if [ "${1:-}" = "postgres" ] || [ "${1:-}" = "docker-entrypoint.sh" ]; then
    set -- "$@" -c "archive_mode=on" \
      -c "archive_timeout=${ARCHIVE_TIMEOUT}" \
      -c "archive_command=pgbackrest --stanza=${STANZA} archive-push %p"
  fi
fi

# Prefer upstream entrypoint when present.
if [ -x /usr/local/bin/docker-entrypoint.sh ]; then
  exec /usr/local/bin/docker-entrypoint.sh "$@"
fi
exec docker-entrypoint.sh "$@"
